# Generated by Django 5.1.6 on 2025-02-21 10:29

import filehub.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('image', filehub.fields.ImagePickerField(verbose_name='Image')),
                ('category', models.CharField(choices=[('vision', 'vision'), ('About', 'About'), ('exit', 'exit')], default='About', max_length=20)),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'about',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Message',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Home', 'Home'), ('About', 'About')], default='Home', max_length=20)),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='practicearea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', filehub.fields.ImagePickerField()),
            ],
            options={
                'verbose_name': 'practice Area',
                'verbose_name_plural': 'Practice Area',
            },
        ),
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('image', filehub.fields.ImagePickerField(verbose_name='Image')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('image', filehub.fields.ImagePickerField(verbose_name='Image')),
            ],
            options={
                'verbose_name': 'services',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('position', models.CharField(max_length=200)),
                ('lawyer_image', filehub.fields.ImagePickerField()),
                ('description', tinymce.models.HTMLField(verbose_name='description')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('number', models.IntegerField(null=True, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['number', '-id'],
            },
        ),
    ]
