# Generated by Django 5.1.6 on 2025-03-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_practicearea_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicearea',
            options={},
        ),
    ]
