# Generated by Django 5.1.6 on 2025-02-07 06:21

import filehub.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=filehub.fields.ImagePickerField(),
        ),
    ]
