# Generated by Django 5.1 on 2025-02-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_productdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdescription',
            name='product',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='image',
            new_name='Lawyer_image',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_list_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
