# Generated by Django 5.1 on 2025-02-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_productdescription_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='TeamMemberDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_list_item', models.BooleanField(default=False)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='core.teammember')),
            ],
        ),
    ]
