# Generated by Django 5.1 on 2025-02-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_teammember_description_teammemberdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='Lawyer_image',
            new_name='lawyer_image',
        ),
    ]
