# Generated by Django 5.1 on 2025-02-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_lawyer_image_teammember_lawyer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(default='rajesh'),
            preserve_default=False,
        ),
    ]
