# Generated by Django 5.1 on 2025-02-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teammember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
