# Generated by Django 5.1.6 on 2025-02-11 07:19

import filehub.fields
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsection',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='image',
            field=filehub.fields.ImagePickerField(),
        ),
        migrations.AlterField(
            model_name='teammemberdescription',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='teammemberdescription',
            name='topic',
            field=tinymce.models.HTMLField(max_length=100),
        ),
    ]
