# Generated by Django 5.1.6 on 2025-02-11 07:40

import django.db.models.deletion
import filehub.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_contentsection_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsection',
            options={'verbose_name': 'Content Section', 'verbose_name_plural': 'Content Sections'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='teammemberdescription',
            options={'verbose_name': 'Team Member Description', 'verbose_name_plural': 'Team Member Descriptions'},
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='image',
            field=filehub.fields.ImagePickerField(verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_list_item',
            field=models.BooleanField(default=False, verbose_name='Is List Item'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='lawyer_image',
            field=filehub.fields.ImagePickerField(verbose_name='Lawyer Image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='teammemberdescription',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='teammemberdescription',
            name='is_list_item',
            field=models.BooleanField(default=False, verbose_name='Is List Item'),
        ),
        migrations.AlterField(
            model_name='teammemberdescription',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='core.teammember', verbose_name='Team Member'),
        ),
        migrations.AlterField(
            model_name='teammemberdescription',
            name='topic',
            field=tinymce.models.HTMLField(max_length=100, verbose_name='Topic'),
        ),
    ]
