# Generated by Django 5.1.6 on 2025-02-11 10:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contentsection_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentSection',
            new_name='publication',
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'publication', 'verbose_name_plural': 'publications'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
