# Generated by Django 5.1.6 on 2025-02-11 16:34

import filehub.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_contentsection_publication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='is_list_item',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='lawyer_image',
            field=filehub.fields.ImagePickerField(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='TeamMemberDescription',
        ),
    ]
