# Generated by Django 5.1.6 on 2025-02-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_teammember_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['number', '-id'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
