# Generated by Django 5.1.6 on 2025-02-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_teammember_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Order Number'),
        ),
    ]
