# Generated by Django 5.1.6 on 2025-02-12 09:08

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_teammember_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='publication',
            new_name='services',
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='number',
            field=models.IntegerField(null=True, verbose_name='order'),
        ),
    ]
