# Generated by Django 5.1.6 on 2025-02-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_publication_services_alter_services_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='publication',
            fields=[
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.services',),
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'services', 'verbose_name_plural': 'services'},
        ),
    ]
