# Generated by Django 5.1.6 on 2025-02-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_publication_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_services',
            field=models.BooleanField(default=True),
        ),
    ]
