# Generated by Django 5.1.6 on 2025-02-13 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_teammember_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='publication',
        ),
        migrations.CreateModel(
            name='publication',
            fields=[
                ('services_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.services')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
            },
            bases=('core.services',),
        ),
    ]
