# Generated by Django 5.1.6 on 2025-02-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_publication_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('homefaq', 'homefaq'), ('aboutfaq', 'aboutfaq')], default='homefaq', max_length=20),
        ),
    ]
