# Generated by Django 5.1.6 on 2025-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_faq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('About', 'About')], default='Home', max_length=20),
        ),
    ]
