# Generated by Django 5.1.6 on 2025-02-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='category',
            field=models.CharField(choices=[('vision', 'vision'), ('About', 'About'), ('exit', 'exit')], default='About', max_length=20),
        ),
    ]
