"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!*%xi(^=3cthwyc%(fb^^o(^j9=%8v$^ofs5vn)knj+8my4kw$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'dashub',
    'django_bleach',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filehub',
    'core',
    'tinymce',
    'debug_toolbar'
    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware'

]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DASHHUB_SETTINGS = {
    "site_logo": "http://127.0.0.1:8000/static/image/logo.png",
    "theme_color": "#009688",
    "custom_css": "admin/css/custom.css",
    "hide_models": [
        "auth.group",
        "auth.user",
    ],
    "icons": {
        "core.publication": "fa-solid fa-book-open",
        "core.faq": "fa-solid fa-circle-question",
        "core.TeamMember": "fa-solid fa-user",
        "core.about": "fa-solid fa-user",
        "core.ContactMessage": "fa-solid fa-envelope",
        "core.practiceArea": "fa-solid fa-briefcase",
        "core.services": "fa-solid fa-cogs"
},


    "default_orders": {
    "core.teammember": 3,
    "core.faq": 1,
    "core.publication": 2,
    },
    "sidebar_search": True,
    "sidebar_search_placeholder": "Search..."

}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

X_FRAME_OPTIONS = "SAMEORIGIN"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



STATIC_URL = '/static/'  
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Your existing static files

# Add this:
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Where collectstatic will store files


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
DIRECTORY = "uploads"


FILE_TYPE_CATEGORIES = {
    'images': ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp'],
    'videos': ['mp4', 'webm', 'ogg', 'avi', 'mkv', 'mov', 'wmv', '3gp', 'mpeg', 'mpg4'],
    'musics': ['mp3', 'wav', 'flac', 'aac', 'wma', 'm4a'],
    'archives': ['zip', 'rar', 'tar', 'gz']
}

FILEHUB_THEME_COLOR = "#3498db"

# Tinymce Configuration
TINYMCE_JS_URL = "https://cdnjs.cloudflare.com/ajax/libs/tinymce/7.5.1/tinymce.min.js"
TINYMCE_DEFAULT_CONFIG = {
    "promotion": False,
    "menubar": "file edit view insert format tools table",
    "plugins": "codesample link media image code fullscreen filehub table autolink advlist lists autoresize emoticons "
               "wordcount",
    "toolbar": [
        "bold italic underline strikethrough | subscript superscript | list bullist numlist blockquote alignleft "
        "aligncenter alignright alignjustify autolink link table",
        "styles forecolor |  subscript superscript | outdent indent | filehub image media emoticons | "
        "wordcount codesample fullscreen code"
    ],
    "image_advtab": False,
    "external_filemanager_path": "/admin/fm/select/",
    "filemanager_title": "Filemanager",
    "external_plugins": {
        "filehub": "/static/filehub/plugin.min.js"
    },
    "relative_urls": False,
    "remove_script_host": True,
    "toolbar_sticky": True,
    "image_dimensions": False,
    "noneditable_noneditable_class": 'alert',
    "min_height": 300,
    "content_css": 'light',
    "license_key": "gpl",
}